spring.application.name=SeatLock
spring.datasource.url=jdbc:postgresql://localhost:5432/seatlock
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate

spring.data.redis.host=localhost
spring.data.redis.port=6379