spring.application.name=SeatLock
spring.datasource.url=jdbc:postgresql://localhost:5432/seatlock
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=validate

spring.data.redis.host=localhost
spring.data.redis.port=6379

logging.level.com.ShikharKothari0.SeatLock.service=DEBUG

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=seatlock-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
# separate consumer group configs
spring.kafka.consumer.properties.spring.json.trusted.packages=com.ShikharKothari0.SeatLock.kafka.event
spring.kafka.listener.concurrency=3
spring.kafka.listener.ack-mode=RECORD

# Resilience4j circuit breaker: redis-lock
resilience4j.circuitbreaker.instances.redisLock.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.redisLock.sliding-window-size=10
resilience4j.circuitbreaker.instances.redisLock.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.redisLock.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.redisLock.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.redisLock.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.redisLock.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.redisLock.register-health-indicator=true

# expose circuit breaker state via Actuator
management.endpoints.web.exposure.include=health,info, prometheus, circuitbreakers, circuitbreakerevents, metrics
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# Resilience4j circuit breaker: redisCache
resilience4j.circuitbreaker.instances.redisCache.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.instances.redisCache.sliding-window-size=10
resilience4j.circuitbreaker.instances.redisCache.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.redisCache.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.redisCache.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.redisCache.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.redisCache.automatic-transition-from-open-to-half-open-enabled=true
resilience4j.circuitbreaker.instances.redisCache.register-health-indicator=true
resilience4j.circuitbreaker.instances.redisCache.record-exceptions=org.springframework.data.redis.RedisConnectionFailureException,org.springframework.dao.QueryTimeoutException,io.lettuce.core.RedisConnectionException

# Rate limiting: seat hold endpoint
seatlock.ratelimit.hold.max-requests=5
seatlock.ratelimit.hold.window-seconds=10
